sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install avahi-daemon libavahi-compat-libdnssd-dev
language: elixir
elixir:
    - 1.1.0
    - 1.2.0
otp_release:
    - 17.5
    - 18.0
    - 18.2
script: "MIX_ENV=test mix do deps.get, deps.compile, conform.effective, release, test --cover"
